services:
  postgres:
    image: postgres:15
    container_name: task_management_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: task_management