spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    enabled: false

jwt:
  enabled: true
  secret: ${JWT_SECRET}

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS}