spring:
  application:
    name: todolist
  profiles:
    active: dev  # Default profile
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

cors:
  allowed:
    origins: http://localhost:8080, http://localhost:3000

springdoc:
  api-docs:
    path: /api-docs

app:
  upload:
    dir: images/