spring:
  application:
    name: todolist
  profiles:
    active: dev  # Default profile
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB


springdoc:
  api-docs:
    path: /api-docs

app:
  upload:
    dir: images/