CREATE SEQUENCE  IF NOT EXISTS tag_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS tag (
    id BIGINT PRIMARY KEY,
    name VARCHAR2(255)
);

ALTER TABLE tag ALTER COLUMN id SET DEFAULT nextval('tag_sequence');

CREATE TABLE IF NOT EXISTS tasks_tags (
    task_id BIGINT REFERENCES task(id) ON DELETE CASCADE,
    tag_id BIGINT REFERENCES tag(id) ON DELETE CASCADE
);