name: CI Workflow

on:
  pull_request:
    branches: [main]


jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run spotless check
        run: ./gradlew spotlessCheck
  test:
    runs-on: ubuntu-latest
    needs: verify
    env:
      SPRING_PROFILES_ACTIVE: test
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_URL: jdbc:postgresql://localhost:5432/test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run unit tests and generate coverage
        run: ./gradlew test jacocoTestReport

      - name: Fail if coverage < 50%
        run: |
          COVERED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" build/reports/jacoco/test/jacocoTestReport.xml)
          MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" build/reports/jacoco/test/jacocoTestReport.xml)
          TOTAL=$((COVERED + MISSED))
          PERCENT=$((COVERED * 100 / TOTAL))
          echo "Instruction coverage: $PERCENT%"
          if [ "$PERCENT" -lt 30 ]; then
            echo "❌ Coverage below 30%."
            exit 1
          else
            echo "✅ Coverage is good."
          fi


